server {
  listen 80;
  server_name localhost;
  
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Redirige todo al index.html para que el Angular Router funcione (SPA)
    try_files $uri $uri/ /index.html;
  }

  # Configuración opcional para redirigir peticiones API locales hacia PocketBase
  # Si en environment.prod.ts pusiste /pb-api como base URL:
  location /pb-api {
    proxy_pass http://pocketbase:8090/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
